// GENERATED BY CONDUCTOR AT SIGNING — the signed exit criterion of
// epic 11058ffd-76f0-4910-995c-7036eab5d223, phase 0, as an executable guard.
// Keep it: it is your acceptance, and it stays true only while the tree does.
//
// The criterion, verbatim:
//   src/recordsLoader.js exports loadRecords() and a test demonstrates it returns an array; no file outside the workspace is created and nothing is pushed to main.
// sha256: 614937684d0b97cfe89208dca2189b28ad6e1db140923b4cfdfafb7f442776d7
//
// Guarded here: 1 file(s), 1 exported symbol(s).
// Nothing in the criterion was left unguarded by this file's own limits.
// A symbol is checked textually — an export of that name in a named file, or a reference
// (import or call) to it in a named file — never by importing your module.
// A named file is asserted only when this tree can hold it: a slash-less token with an
// extension no file here carries (rows.length) and a path this tree's .gitignore ignores
// (a runtime artefact) are SKIPPED by name, never asserted and never silently passed.

import { test } from "node:test";
import assert from "node:assert/strict";
import { existsSync, readFileSync, readdirSync, statSync } from "node:fs";
import { join } from "node:path";

const FILES = ["src/recordsLoader.js"];
const SYMBOLS = ["loadRecords"];

const read = (p) => (existsSync(p) && statSync(p).isFile() ? readFileSync(p, "utf8") : "");
const walk = (dir, out = []) => {
  if (!existsSync(dir)) return out;
  for (const name of readdirSync(dir)) {
    const p = join(dir, name);
    if (name === "node_modules" || name.startsWith(".")) continue;
    if (statSync(p).isDirectory()) walk(p, out);
    else if (/\.(m?[jt]sx?|cjs)$/.test(name)) out.push(p);
  }
  return out;
};
const exportsSymbol = (src, name) =>
  new RegExp(
    "export\\s+(?:default\\s+)?(?:async\\s+)?(?:function\\*?|const|let|var|class)\\s+" +
      name +
      "\\b|export\\s*\\{[^}]*\\b" +
      name +
      "\\b[^}]*\\}|module\\.exports\\s*=\\s*\\{[^}]*\\b" +
      name +
      "\\b|exports\\." +
      name +
      "\\s*=",
  ).test(src);

// ⚠️ TWO WAYS A "FILE" IN A CRITERION IS NOT A FILE, both derived from THIS
// tree rather than declared (run 8feffcc5, 2026-08-28: "count equal to
// rows.length" was asserted as a file named rows with extension .length, and
// the phase failed with its own 18 tests green):
//   1. a slash-less token whose extension no file in the tree carries reads as
//      a property access (rows.length, now.toISOString) — not asserted, said;
//   2. a path the tree's own .gitignore ignores is a runtime artefact the
//      criterion NAMES rather than one the repository CONTAINS (public/prices.json
//      written each cycle) — not asserted, said.
// Both are SKIPS with the reason in the test name, never passes.
//   3. a slash-less token is a NAME, not a root path: "RiskPage.tsx calls
//      readCurrentPrice()" means src/pages/RiskPage.tsx. It is resolved by
//      basename anywhere in the tree (2026-08-29: a guard asserted RiskPage.tsx
//      at the root and would have failed the phase on correct work).
const { extsInTree, byBasename, allPaths } = (() => {
  const exts = new Set();
  const names = new Map();
  const all = [];
  const walkAll = (dir) => {
    if (!existsSync(dir)) return;
    for (const name of readdirSync(dir)) {
      if (name === "node_modules" || name === ".git") continue;
      const p = join(dir, name);
      if (statSync(p).isDirectory()) walkAll(p);
      else {
        const rel = p.replace(/\\/g, "/").replace(/^\.\//, "");
        all.push(rel);
        if (name.includes(".")) exts.add(name.slice(name.lastIndexOf(".") + 1).toLowerCase());
        if (!names.has(name)) names.set(name, rel);
      }
    }
  };
  walkAll(".");
  return { extsInTree: exts, byBasename: names, allPaths: all };
})();
const ignoredByTree = (() => {
  const lines = read(".gitignore").split(/\r?\n/).map((l) => l.trim()).filter((l) => l && !l.startsWith("#") && !l.startsWith("!"));
  const pats = lines.map((l) => l.replace(/^\//, "").replace(/\/$/, ""));
  return (p) =>
    pats.some((pat) => {
      if (!/[*?\[]/.test(pat)) return p === pat || p.startsWith(pat + "/") || p.split("/").includes(pat);
      const re = new RegExp("^" + pat.replace(/[.+^${}()|\\]/g, "\\$&").replace(/\*/g, "[^/]*").replace(/\?/g, "[^/]") + "$");
      return re.test(p) || re.test(p.split("/").pop());
    });
})();

for (const f of FILES) {
  const ext = f.includes(".") ? f.slice(f.lastIndexOf(".") + 1).toLowerCase() : "";
  if (!f.includes("/") && !extsInTree.has(ext)) {
    test(`criterion names ${f} — no file in this tree has the extension .${ext}; it reads as a property access, not a file — NOT asserted`, { skip: "not a file in this tree's vocabulary" }, () => {});
    continue;
  }
  if (ignoredByTree(f)) {
    test(`criterion names ${f} — the tree's own .gitignore ignores it: a runtime artefact the criterion names, not one the repository contains — NOT asserted`, { skip: "ignored by .gitignore" }, () => {});
    continue;
  }
  if (!f.includes("/")) {
    // the tokenizer cannot take a leading dot, so ".env.example" arrives as
    // "env.example": a dotfile of that name satisfies it (schema epic p2, 2026-08-29)
    // (no backticks in this comment: it lives inside the generated template)
    const at = byBasename.get(f) ?? byBasename.get("." + f);
    test(`criterion names ${f} — a file of that name exists somewhere in the tree${at ? " (" + at + ")" : ""}`, () => {
      assert.ok(at, `no file named ${f} anywhere in the tree — the signed criterion names it`);
    });
    continue;
  }
  // a slashed path absent at the root may be a SUFFIX of exactly one tree path
  // ("fetch-historical-data/index.ts" for supabase/functions/fetch-historical-data/index.ts)
  const suffixHits = existsSync(f) ? [] : allPaths.filter((p) => p.endsWith("/" + f));
  if (!existsSync(f) && suffixHits.length === 1) {
    test(`criterion names ${f} — it exists as ${suffixHits[0]}`, () => {
      assert.ok(existsSync(suffixHits[0]));
    });
    continue;
  }
  test(`criterion names ${f} — it exists`, () => {
    assert.ok(existsSync(f), `${f} is named by the signed criterion and is not in the tree`);
  });
}

// a named symbol is satisfied by a named file that EXPORTS it, or one that
// REFERENCES it (imports or calls it) — a criterion names what a phase makes
// AND what it wires; "digest.mjs calls buildDigest()" is the second kind
const referencesSymbol = (src, name) =>
  new RegExp("\\b" + name + "\\s*\\(|import\\s*\\{[^}]*\\b" + name + "\\b[^}]*\\}").test(src);

for (const s of SYMBOLS) {
  test(`criterion names ${s} — a named file exports or references it`, () => {
    const resolveNamed = (f) => {
      if (!f.includes("/")) return byBasename.get(f) ?? byBasename.get("." + f);
      if (existsSync(f)) return f;
      const hits = allPaths.filter((p) => p.endsWith("/" + f));
      return hits.length === 1 ? hits[0] : null;
    };
    const named = FILES.map(resolveNamed).filter((f) => f && existsSync(f));
    const candidates = FILES.length ? named : walk("src");
    const hit = candidates.find((f) => {
      const src = read(f);
      return exportsSymbol(src, s) || (FILES.length > 0 && referencesSymbol(src, s));
    });
    assert.ok(
      hit,
      `${s} is named by the signed criterion and no ${FILES.length ? "named file exports or references" : "file under src/ exports"} it`,
    );
  });
}
